"""empty message

Revision ID: 14f3e209ca63
Revises: a4bed8ac5130
Create Date: 2022-02-10 23:43:46.963276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f3e209ca63'
down_revision = 'a4bed8ac5130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('rate_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'rate_number')
    # ### end Alembic commands ###
