"""empty message

Revision ID: 2533b81e6925
Revises: 7233c351a36f
Create Date: 2022-02-02 21:53:26.295460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2533b81e6925'
down_revision = '7233c351a36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drummers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drummer_name', sa.String(length=100), nullable=True),
    sa.Column('wikipedia', sa.String(length=3000), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('Born', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drummers_drummer_name'), 'drummers', ['drummer_name'], unique=False)
    op.create_index(op.f('ix_drummers_gender'), 'drummers', ['gender'], unique=False)
    op.create_index(op.f('ix_drummers_wikipedia'), 'drummers', ['wikipedia'], unique=False)
    op.create_table('guitarists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guitarist_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guitarists_guitarist_name'), 'guitarists', ['guitarist_name'], unique=False)
    op.create_table('pianists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pianist_name', sa.String(length=100), nullable=True),
    sa.Column('wikipedia', sa.String(length=3000), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('Born', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pianists_gender'), 'pianists', ['gender'], unique=False)
    op.create_index(op.f('ix_pianists_pianist_name'), 'pianists', ['pianist_name'], unique=False)
    op.create_index(op.f('ix_pianists_wikipedia'), 'pianists', ['wikipedia'], unique=False)
    op.create_table('writers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('writer_name', sa.String(length=100), nullable=True),
    sa.Column('wikipedia', sa.String(length=3000), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('Born', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writers_gender'), 'writers', ['gender'], unique=False)
    op.create_index(op.f('ix_writers_wikipedia'), 'writers', ['wikipedia'], unique=False)
    op.create_index(op.f('ix_writers_writer_name'), 'writers', ['writer_name'], unique=False)
    op.create_table('drummer_relation',
    sa.Column('drummer_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drummer_id'], ['drummers.id'], ),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], )
    )
    op.create_table('guitarist_relation',
    sa.Column('guitarist_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guitarist_id'], ['guitarists.id'], ),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], )
    )
    op.create_table('pianist_relation',
    sa.Column('pianist_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.ForeignKeyConstraint(['pianist_id'], ['pianists.id'], )
    )
    op.create_table('writer_relation',
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['writers.id'], )
    )
    op.add_column('music', sa.Column('lyric', sa.String(length=3000), nullable=True))
    op.add_column('music', sa.Column('tags', sa.String(length=100), nullable=True))
    op.add_column('music', sa.Column('audio_file_name', sa.String(length=100), nullable=True))
    op.add_column('music', sa.Column('reviews', sa.String(length=6000), nullable=True))
    op.create_index(op.f('ix_music_audio_file_name'), 'music', ['audio_file_name'], unique=False)
    op.create_index(op.f('ix_music_lyric'), 'music', ['lyric'], unique=False)
    op.create_index(op.f('ix_music_reviews'), 'music', ['reviews'], unique=False)
    op.create_index(op.f('ix_music_tags'), 'music', ['tags'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_music_tags'), table_name='music')
    op.drop_index(op.f('ix_music_reviews'), table_name='music')
    op.drop_index(op.f('ix_music_lyric'), table_name='music')
    op.drop_index(op.f('ix_music_audio_file_name'), table_name='music')
    op.drop_column('music', 'reviews')
    op.drop_column('music', 'audio_file_name')
    op.drop_column('music', 'tags')
    op.drop_column('music', 'lyric')
    op.drop_table('writer_relation')
    op.drop_table('pianist_relation')
    op.drop_table('guitarist_relation')
    op.drop_table('drummer_relation')
    op.drop_index(op.f('ix_writers_writer_name'), table_name='writers')
    op.drop_index(op.f('ix_writers_wikipedia'), table_name='writers')
    op.drop_index(op.f('ix_writers_gender'), table_name='writers')
    op.drop_table('writers')
    op.drop_index(op.f('ix_pianists_wikipedia'), table_name='pianists')
    op.drop_index(op.f('ix_pianists_pianist_name'), table_name='pianists')
    op.drop_index(op.f('ix_pianists_gender'), table_name='pianists')
    op.drop_table('pianists')
    op.drop_index(op.f('ix_guitarists_guitarist_name'), table_name='guitarists')
    op.drop_table('guitarists')
    op.drop_index(op.f('ix_drummers_wikipedia'), table_name='drummers')
    op.drop_index(op.f('ix_drummers_gender'), table_name='drummers')
    op.drop_index(op.f('ix_drummers_drummer_name'), table_name='drummers')
    op.drop_table('drummers')
    # ### end Alembic commands ###
