"""empty message

Revision ID: 6dbc6c10e0f0
Revises: 
Create Date: 2022-03-24 04:16:49.679533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbc6c10e0f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_nominates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nominate_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_nominates_nominate_name'), 'album_nominates', ['nominate_name'], unique=False)
    op.create_table('album_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review', sa.String(length=1000), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_reviews_review'), 'album_reviews', ['review'], unique=False)
    op.create_table('albums',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('album_name', sa.String(length=100), nullable=True),
    sa.Column('publish_year', sa.DateTime(), nullable=True),
    sa.Column('album_wiki', sa.String(length=3000), nullable=True),
    sa.Column('album_rating', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('rate_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_album_name'), 'albums', ['album_name'], unique=False)
    op.create_index(op.f('ix_albums_album_wiki'), 'albums', ['album_wiki'], unique=False)
    op.create_table('artist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artist_name', sa.String(length=50), nullable=True),
    sa.Column('wikipedia', sa.String(length=3000), nullable=True),
    sa.Column('tags', sa.String(length=1000), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('Born', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_artist_name'), 'artist', ['artist_name'], unique=False)
    op.create_index(op.f('ix_artist_gender'), 'artist', ['gender'], unique=False)
    op.create_index(op.f('ix_artist_tags'), 'artist', ['tags'], unique=False)
    op.create_index(op.f('ix_artist_wikipedia'), 'artist', ['wikipedia'], unique=False)
    op.create_table('bands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('band_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bands_band_name'), 'bands', ['band_name'], unique=False)
    op.create_table('drummers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drummer_name', sa.String(length=100), nullable=True),
    sa.Column('wikipedia', sa.String(length=3000), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('Born', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drummers_drummer_name'), 'drummers', ['drummer_name'], unique=False)
    op.create_index(op.f('ix_drummers_gender'), 'drummers', ['gender'], unique=False)
    op.create_index(op.f('ix_drummers_wikipedia'), 'drummers', ['wikipedia'], unique=False)
    op.create_table('electric_guitarists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('electric_guitarist_name', sa.String(length=100), nullable=True),
    sa.Column('wikipedia', sa.String(length=3000), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('Born', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electric_guitarists_electric_guitarist_name'), 'electric_guitarists', ['electric_guitarist_name'], unique=False)
    op.create_index(op.f('ix_electric_guitarists_gender'), 'electric_guitarists', ['gender'], unique=False)
    op.create_index(op.f('ix_electric_guitarists_wikipedia'), 'electric_guitarists', ['wikipedia'], unique=False)
    op.create_table('guitarists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guitarist_name', sa.String(length=100), nullable=True),
    sa.Column('wikipedia', sa.String(length=3000), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('Born', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guitarists_gender'), 'guitarists', ['gender'], unique=False)
    op.create_index(op.f('ix_guitarists_guitarist_name'), 'guitarists', ['guitarist_name'], unique=False)
    op.create_index(op.f('ix_guitarists_wikipedia'), 'guitarists', ['wikipedia'], unique=False)
    op.create_table('mixers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mixer_name', sa.String(length=100), nullable=True),
    sa.Column('wikipedia', sa.String(length=3000), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('Born', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mixers_gender'), 'mixers', ['gender'], unique=False)
    op.create_index(op.f('ix_mixers_mixer_name'), 'mixers', ['mixer_name'], unique=False)
    op.create_index(op.f('ix_mixers_wikipedia'), 'mixers', ['wikipedia'], unique=False)
    op.create_table('music_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review', sa.String(length=1000), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_reviews_review'), 'music_reviews', ['review'], unique=False)
    op.create_table('music_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_tag_tag_name'), 'music_tag', ['tag_name'], unique=False)
    op.create_table('nominates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nominate_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nominates_nominate_name'), 'nominates', ['nominate_name'], unique=False)
    op.create_table('pianists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pianist_name', sa.String(length=100), nullable=True),
    sa.Column('wikipedia', sa.String(length=3000), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('Born', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pianists_gender'), 'pianists', ['gender'], unique=False)
    op.create_index(op.f('ix_pianists_pianist_name'), 'pianists', ['pianist_name'], unique=False)
    op.create_index(op.f('ix_pianists_wikipedia'), 'pianists', ['wikipedia'], unique=False)
    op.create_table('tours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tour_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_tour_name'), 'tours', ['tour_name'], unique=False)
    op.create_table('writers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('writer_name', sa.String(length=100), nullable=True),
    sa.Column('wikipedia', sa.String(length=3000), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('Born', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writers_gender'), 'writers', ['gender'], unique=False)
    op.create_index(op.f('ix_writers_wikipedia'), 'writers', ['wikipedia'], unique=False)
    op.create_index(op.f('ix_writers_writer_name'), 'writers', ['writer_name'], unique=False)
    op.create_table('album_nominate_relation',
    sa.Column('album_nominate_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['album_nominate_id'], ['album_nominates.id'], )
    )
    op.create_table('album_relation',
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], )
    )
    op.create_table('album_review_relation',
    sa.Column('album_review_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['album_review_id'], ['album_reviews.id'], )
    )
    op.create_table('band_relation',
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], )
    )
    op.create_table('music',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('music_name', sa.String(length=100), nullable=True),
    sa.Column('music_story', sa.String(length=3000), nullable=True),
    sa.Column('lyric', sa.String(length=3000), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('audio_file_name', sa.String(length=100), nullable=True),
    sa.Column('yt_link', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_audio_file_name'), 'music', ['audio_file_name'], unique=False)
    op.create_index(op.f('ix_music_lyric'), 'music', ['lyric'], unique=False)
    op.create_index(op.f('ix_music_music_name'), 'music', ['music_name'], unique=False)
    op.create_index(op.f('ix_music_music_story'), 'music', ['music_story'], unique=False)
    op.create_index(op.f('ix_music_yt_link'), 'music', ['yt_link'], unique=False)
    op.create_table('nominate_relation',
    sa.Column('nominate_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['nominate_id'], ['nominates.id'], )
    )
    op.create_table('teach',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'student_id')
    )
    op.create_table('tour_relation',
    sa.Column('tour_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], )
    )
    op.create_table('tribute',
    sa.Column('tributed_artist_id', sa.Integer(), nullable=False),
    sa.Column('tribute_to_artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tribute_to_artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['tributed_artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('tributed_artist_id', 'tribute_to_artist_id')
    )
    op.create_table('drummer_relation',
    sa.Column('drummer_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drummer_id'], ['drummers.id'], ),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], )
    )
    op.create_table('electric_guitarist_relation',
    sa.Column('electric_guitarist_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['electric_guitarist_id'], ['electric_guitarists.id'], ),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], )
    )
    op.create_table('guitarist_relation',
    sa.Column('guitarist_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guitarist_id'], ['guitarists.id'], ),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], )
    )
    op.create_table('mixer_relation',
    sa.Column('mixer_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mixer_id'], ['mixers.id'], ),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], )
    )
    op.create_table('music_and_tag_relation',
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['music_tag.id'], ),
    sa.PrimaryKeyConstraint('music_id', 'tag_id')
    )
    op.create_table('music_review_relation',
    sa.Column('music_review_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.ForeignKeyConstraint(['music_review_id'], ['music_reviews.id'], )
    )
    op.create_table('pianist_relation',
    sa.Column('pianist_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.ForeignKeyConstraint(['pianist_id'], ['pianists.id'], )
    )
    op.create_table('writer_relation',
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['writers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writer_relation')
    op.drop_table('pianist_relation')
    op.drop_table('music_review_relation')
    op.drop_table('music_and_tag_relation')
    op.drop_table('mixer_relation')
    op.drop_table('guitarist_relation')
    op.drop_table('electric_guitarist_relation')
    op.drop_table('drummer_relation')
    op.drop_table('tribute')
    op.drop_table('tour_relation')
    op.drop_table('teach')
    op.drop_table('nominate_relation')
    op.drop_index(op.f('ix_music_yt_link'), table_name='music')
    op.drop_index(op.f('ix_music_music_story'), table_name='music')
    op.drop_index(op.f('ix_music_music_name'), table_name='music')
    op.drop_index(op.f('ix_music_lyric'), table_name='music')
    op.drop_index(op.f('ix_music_audio_file_name'), table_name='music')
    op.drop_table('music')
    op.drop_table('band_relation')
    op.drop_table('album_review_relation')
    op.drop_table('album_relation')
    op.drop_table('album_nominate_relation')
    op.drop_index(op.f('ix_writers_writer_name'), table_name='writers')
    op.drop_index(op.f('ix_writers_wikipedia'), table_name='writers')
    op.drop_index(op.f('ix_writers_gender'), table_name='writers')
    op.drop_table('writers')
    op.drop_index(op.f('ix_tours_tour_name'), table_name='tours')
    op.drop_table('tours')
    op.drop_index(op.f('ix_pianists_wikipedia'), table_name='pianists')
    op.drop_index(op.f('ix_pianists_pianist_name'), table_name='pianists')
    op.drop_index(op.f('ix_pianists_gender'), table_name='pianists')
    op.drop_table('pianists')
    op.drop_index(op.f('ix_nominates_nominate_name'), table_name='nominates')
    op.drop_table('nominates')
    op.drop_index(op.f('ix_music_tag_tag_name'), table_name='music_tag')
    op.drop_table('music_tag')
    op.drop_index(op.f('ix_music_reviews_review'), table_name='music_reviews')
    op.drop_table('music_reviews')
    op.drop_index(op.f('ix_mixers_wikipedia'), table_name='mixers')
    op.drop_index(op.f('ix_mixers_mixer_name'), table_name='mixers')
    op.drop_index(op.f('ix_mixers_gender'), table_name='mixers')
    op.drop_table('mixers')
    op.drop_index(op.f('ix_guitarists_wikipedia'), table_name='guitarists')
    op.drop_index(op.f('ix_guitarists_guitarist_name'), table_name='guitarists')
    op.drop_index(op.f('ix_guitarists_gender'), table_name='guitarists')
    op.drop_table('guitarists')
    op.drop_index(op.f('ix_electric_guitarists_wikipedia'), table_name='electric_guitarists')
    op.drop_index(op.f('ix_electric_guitarists_gender'), table_name='electric_guitarists')
    op.drop_index(op.f('ix_electric_guitarists_electric_guitarist_name'), table_name='electric_guitarists')
    op.drop_table('electric_guitarists')
    op.drop_index(op.f('ix_drummers_wikipedia'), table_name='drummers')
    op.drop_index(op.f('ix_drummers_gender'), table_name='drummers')
    op.drop_index(op.f('ix_drummers_drummer_name'), table_name='drummers')
    op.drop_table('drummers')
    op.drop_index(op.f('ix_bands_band_name'), table_name='bands')
    op.drop_table('bands')
    op.drop_index(op.f('ix_artist_wikipedia'), table_name='artist')
    op.drop_index(op.f('ix_artist_tags'), table_name='artist')
    op.drop_index(op.f('ix_artist_gender'), table_name='artist')
    op.drop_index(op.f('ix_artist_artist_name'), table_name='artist')
    op.drop_table('artist')
    op.drop_index(op.f('ix_albums_album_wiki'), table_name='albums')
    op.drop_index(op.f('ix_albums_album_name'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_album_reviews_review'), table_name='album_reviews')
    op.drop_table('album_reviews')
    op.drop_index(op.f('ix_album_nominates_nominate_name'), table_name='album_nominates')
    op.drop_table('album_nominates')
    # ### end Alembic commands ###
