"""empty message

Revision ID: 7233c351a36f
Revises: 
Create Date: 2022-02-02 21:26:23.570549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7233c351a36f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('album_name', sa.String(length=100), nullable=True),
    sa.Column('publish_year', sa.Integer(), nullable=True),
    sa.Column('album_wiki', sa.String(length=3000), nullable=True),
    sa.Column('album_reviews', sa.String(length=6000), nullable=True),
    sa.Column('album_rating', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_album_name'), 'albums', ['album_name'], unique=False)
    op.create_index(op.f('ix_albums_album_reviews'), 'albums', ['album_reviews'], unique=False)
    op.create_index(op.f('ix_albums_album_wiki'), 'albums', ['album_wiki'], unique=False)
    op.create_table('artist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artist_name', sa.String(length=50), nullable=True),
    sa.Column('wikipedia', sa.String(length=3000), nullable=True),
    sa.Column('tags', sa.String(length=1000), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('Born', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_artist_name'), 'artist', ['artist_name'], unique=False)
    op.create_index(op.f('ix_artist_gender'), 'artist', ['gender'], unique=False)
    op.create_index(op.f('ix_artist_tags'), 'artist', ['tags'], unique=False)
    op.create_index(op.f('ix_artist_wikipedia'), 'artist', ['wikipedia'], unique=False)
    op.create_table('bands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('band_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bands_band_name'), 'bands', ['band_name'], unique=False)
    op.create_table('nominates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nominate_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nominates_nominate_name'), 'nominates', ['nominate_name'], unique=False)
    op.create_table('tours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tour_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_tour_name'), 'tours', ['tour_name'], unique=False)
    op.create_table('album_relation',
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], )
    )
    op.create_table('band_relation',
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], )
    )
    op.create_table('music',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('music_name', sa.String(length=100), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.Column('music_story', sa.String(length=3000), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_music_name'), 'music', ['music_name'], unique=False)
    op.create_index(op.f('ix_music_music_story'), 'music', ['music_story'], unique=False)
    op.create_table('nominate_relation',
    sa.Column('nominate_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['nominate_id'], ['nominates.id'], )
    )
    op.create_table('teach',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'student_id')
    )
    op.create_table('tour_relation',
    sa.Column('tour_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], )
    )
    op.create_table('tribute',
    sa.Column('tributed_artist_id', sa.Integer(), nullable=False),
    sa.Column('tribute_to_artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tribute_to_artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['tributed_artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('tributed_artist_id', 'tribute_to_artist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tribute')
    op.drop_table('tour_relation')
    op.drop_table('teach')
    op.drop_table('nominate_relation')
    op.drop_index(op.f('ix_music_music_story'), table_name='music')
    op.drop_index(op.f('ix_music_music_name'), table_name='music')
    op.drop_table('music')
    op.drop_table('band_relation')
    op.drop_table('album_relation')
    op.drop_index(op.f('ix_tours_tour_name'), table_name='tours')
    op.drop_table('tours')
    op.drop_index(op.f('ix_nominates_nominate_name'), table_name='nominates')
    op.drop_table('nominates')
    op.drop_index(op.f('ix_bands_band_name'), table_name='bands')
    op.drop_table('bands')
    op.drop_index(op.f('ix_artist_wikipedia'), table_name='artist')
    op.drop_index(op.f('ix_artist_tags'), table_name='artist')
    op.drop_index(op.f('ix_artist_gender'), table_name='artist')
    op.drop_index(op.f('ix_artist_artist_name'), table_name='artist')
    op.drop_table('artist')
    op.drop_index(op.f('ix_albums_album_wiki'), table_name='albums')
    op.drop_index(op.f('ix_albums_album_reviews'), table_name='albums')
    op.drop_index(op.f('ix_albums_album_name'), table_name='albums')
    op.drop_table('albums')
    # ### end Alembic commands ###
