"""empty message

Revision ID: a4bed8ac5130
Revises: 10bec1d64a76
Create Date: 2022-02-10 23:37:35.068157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4bed8ac5130'
down_revision = '10bec1d64a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_reviews_review'), 'album_reviews', ['review'], unique=False)
    op.create_table('music_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_reviews_review'), 'music_reviews', ['review'], unique=False)
    op.create_table('album_review_relation',
    sa.Column('album_review_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['album_review_id'], ['album_reviews.id'], )
    )
    op.create_table('music_review_relation',
    sa.Column('music_review_id', sa.Integer(), nullable=True),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.ForeignKeyConstraint(['music_review_id'], ['music_reviews.id'], )
    )
    op.drop_index('ix_albums_album_reviews', table_name='albums')
    op.drop_column('albums', 'album_reviews')
    op.drop_index('ix_music_reviews', table_name='music')
    op.drop_column('music', 'reviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('reviews', mysql.VARCHAR(length=6000), nullable=True))
    op.create_index('ix_music_reviews', 'music', ['reviews'], unique=False)
    op.add_column('albums', sa.Column('album_reviews', mysql.VARCHAR(length=6000), nullable=True))
    op.create_index('ix_albums_album_reviews', 'albums', ['album_reviews'], unique=False)
    op.drop_table('music_review_relation')
    op.drop_table('album_review_relation')
    op.drop_index(op.f('ix_music_reviews_review'), table_name='music_reviews')
    op.drop_table('music_reviews')
    op.drop_index(op.f('ix_album_reviews_review'), table_name='album_reviews')
    op.drop_table('album_reviews')
    # ### end Alembic commands ###
