"""empty message

Revision ID: d887ca80b878
Revises: 14f3e209ca63
Create Date: 2022-02-10 23:45:24.842252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd887ca80b878'
down_revision = '14f3e209ca63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_reviews', sa.Column('rating', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('music_reviews', sa.Column('rating', sa.DECIMAL(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_reviews', 'rating')
    op.drop_column('album_reviews', 'rating')
    # ### end Alembic commands ###
